isacstromberg_dev_site/Models/ErrorViewModel.cs
namespace isacstromberg_dev_site.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

isacstromberg_dev_site/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace isacstromberg_dev_site.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

isacstromberg_dev_site/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace isacstromberg_dev_site.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

isacstromberg_dev_site/Controllers/HomeController.cs
using isacstromberg_dev_site.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace isacstromberg_dev_site.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

isacstromberg_dev_site/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;

namespace isacstromberg_dev_site.Controllers
{
    public class ServicesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

isacstromberg_dev_site/Views/About/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div >
    <h1 class="display-4">Welcome</h1>
    <p>Välkommen till Om oss!</p>
</div>

isacstromberg_dev_site/Views/Contact/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Kontakta mig</h1>
<form action="#" method="post" style="background-color: cornflowerblue; padding: 20px; border-radius: 10px; width: 100%; ">
    <label for="name" style="display: block; margin-bottom: 8px;">Namn:</label>
    <input type="text" id="name" name="name" style="width: 100%; padding: 8px; margin-bottom: 16px; box-sizing: border-box;" required>

    <label for="email" style="display: block; margin-bottom: 8px;">E-post:</label>
    <input type="email" id="email" name="email" style="width: 100%; padding: 8px; margin-bottom: 16px; box-sizing: border-box;" required>

    <label for="message" style="display: block; margin-bottom: 8px;">Meddelande:</label>
    <textarea id="message" name="message" rows="4" style="width: 100%; padding: 8px; margin-bottom: 16px; box-sizing: border-box;" required></textarea>

    <button type="submit" style="background-color: #4CAF50; color: white; width:200px; padding: 20px; border: none; border-radius: 4px; cursor: pointer; margin: auto; display: block;">
        Skicka
    </button>

</form>
<br />
<div id="about" style="display: flex; background-color: cornflowerblue; border-radius: 12px; align-items:center;">

    <img src="\Pictures\ContactPictures\stock_chart_up.jpg" alt="Bild på mig" style=" object-fit:contain; border-radius: 12px; height: 100%; max-height: 200px; margin-right: 20px; flex-shrink: 0;" />

    <p id="about-p" style="font-size: 14px; margin-right: 20px; flex-grow: 1;">
        Att investera i en professionell och välutformad hemsida är en strategisk och lönsamt beslut för alla företag i dagens digitala era.
        En modern och användarvänlig webbplats fungerar som en digital entré och är ofta det första intrycket potentiella kunder får av ditt företag.
        Genom att ha en närvaro på nätet skapar du möjligheter att nå ut till en bredare publik och öka din synlighet på marknaden.

    </p>
</div>

isacstromberg_dev_site/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center" style="background-color:cornflowerblue; border-radius: 20px; padding:10px;">
    <h1 class="display-4" style="color:white;">Strömberg Studios</h1>
    <p style="color: white;">Innovation, pålitlighet och samarbete</p>
</div>
<br />

<section id="hero" class="d-flex align-items-center">


    <video autoplay loop muted playsinline>
        <source src="\Videos\production_id_4828605 (2160p).mp4" type="video/mp4">
       
    </video>
    <div class="text-overlay">
        <h1>Välkommen till Strömberg Studios</h1>
        <p>Vi levererar skräddarsydda IT-lösningar för din verksamhet inom webb.</p>
    </div>
</section>

<br />

<h2 style="color: white; text-align:center">Om mig</h2>

<div id="about" style="display: flex; background-color: cornflowerblue; border-radius: 12px; align-items:center;">

    <img src="\Pictures\pro-AxXBwQzY-2004.jpg" alt="Bild på mig" style=" object-fit:contain; border-radius: 12px; height: 100%; max-height: 300px; margin-right: 20px; flex-shrink: 0;" />
    
    <p id="about-p" style="font-size: 14px; margin-right: 20px; flex-grow: 1;">
        Hej, mitt namn är Isac Strömberg, och jag är stolt grundare av denna webbyrå med fokus på webbutveckling.
        Med en kandidatexamen inom informatik kombinerar jag min passion för kreativ problemlösning med teknisk kompetens för att skapa skräddarsydda webblösningar.
        Varje projekt betraktas som unikt, och jag strävar efter att leverera användarvänliga och visuellt tilltalande webbplatser.
        Kontakta mig gärna för att diskutera hur vi kan förverkliga visionen för din webbplats.
    </p>
</div>
<br />

















<br />
<h2 style="color: white; text-align: center;">Vad jag erbjuder</h2>

<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <br />
            <a asp-controller="Services" asp-action="Index"><img src="\Pictures\photo-1517694712202-14dd9538aa97.jpg" alt="Webbutveckling" class="d-block w-100"></a>
                <p style="text-align:center;">Informationssida</p>
        </div>
        <div class="carousel-item">
            <br />
            <a asp-controller="Services" asp-action="Index"><img src="\Pictures\photo-1511871893393-82e9c16b81e3.jpg" alt="Logotyper" class="d-block w-100"></a>
                <p style="text-align:center;">Bokningssystem</p>
        </div>
        <div class="carousel-item">
            <br />
            <a asp-controller="Services" asp-action="Index"> <img src="\Pictures\photo-1566207474742-de921626ad0c.jpg" alt="Test" class="d-block w-100"></a>
                <p style="text-align:center;">Valfritt projekt</p>
        </div>
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>



<br />
<h2 style="text-align: center; color: white;">Kundreferenser</h2>
<section style="display: flex;">


    <img src="\Pictures\IMG_20190413_191345.jpg" alt="Kundreferens" width="300" height="200" style="display: inline-block; margin-right: 10px; border-radius: 30px" />

    <p style="display: inline-block; font-size: 14px; color : white; border-radius: 20px;  padding: 10px; background-color :cornflowerblue;">
        Lorem ipsum dolor sit amet,
        consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..
        Lorem ipsum dolor sit amet,
        consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..
        Lorem ipsum dolor sit amet,
        consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

    </p>
</section>
<br />
<section style="display: flex;">


    <img src="\Pictures\IMG_20190413_191345.jpg" alt="Kundreferens" width="300" height="200" style="display: inline-block; margin-right: 10px; border-radius: 30px" />

    <p style="display: inline-block; font-size: 14px; color : white; border-radius: 20px;  padding: 10px; background-color :cornflowerblue;">
        Lorem ipsum dolor sit amet,
        consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..
        Lorem ipsum dolor sit amet,
        consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..
        Lorem ipsum dolor sit amet,
        consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

    </p>
</section>

isacstromberg_dev_site/Views/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

isacstromberg_dev_site/Views/Services/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="d-flex align-items-center justify-content-center">
    <h1 class="display-4 text-center" style="background-color: cornflowerblue; border-radius: 20px; padding: 10px; display: inline-block;">
        Mina tjänster
    </h1>


</div>



<br />
<div style="display: flex; justify-content: space-around; gap: 10px; flex-wrap: wrap;">

    <div style="flex: 1; background-color: cornflowerblue; border-radius: 20px; padding: 10px; text-align: center;">
        <h2 class="display-4">Informationssida</h2>
        <p style="font-size: 14px; border-radius: 20px; padding: 10px; background-color: cornflowerblue;">
            En informationssida är en webbplats som främst fungerar som en digital plattform för att presentera och kommunicera information om exempelvis din verksamhet.
            Denna typ av webbplats har som huvudsyfte att exempelvis ge besökare en omfattande översikt över verksamheten, dess produkter, tjänster, och andra relevanta detaljer.
            Genom användning av text, bilder, och ibland multimediaelement som videor,
            strävar informationssidan efter att effektivt kommunicera företagets kärnvärden, mål och eventuella nyheter till potentiella kunder, befintliga kunder och andra intressenter.
            Vanligtvis är gränssnittet intuitivt utformat för att möjliggöra enkel navigering och tillgänglighet, vilket ger besökarna möjlighet att snabbt och lätt hitta den önskade informationen om företaget.
            Informationssidor är en viktig del av en verksamhets online-närvaro och fungerar som ett digitalt visitkort för att etablera och stärka verksamhetens image på internet.
        </p>
    </div>

    <div style="flex: 1; background-color: cornflowerblue; border-radius: 20px; padding: 10px; text-align: center;">
        <h2 class="display-4">Bokningssystem</h2>
        <p style="font-size: 14px; border-radius: 20px; padding: 10px; background-color: cornflowerblue;">
            Ett bokningssystem på en webbplats utgör en centraliserad digital plattform som möjliggör en sömnlös och effektiv hantering av bokningar och reservationer för olika tjänster eller evenemang.
            Genom användning av specialiserade funktioner och interaktiva gränssnitt möjliggör bokningssystemet för användare att enkelt utforska tillgängliga alternativ, välja önskade datum och tider samt slutföra bokningar online.
            Denna typ av webbplats fokuserar på att skapa en bekväm och användarvänlig upplevelse för både företaget och dess kunder.
            Besökare ges möjlighet att boka och bekräfta sina reservationer i realtid, vilket minskar administrativt arbete och förbättrar kundnöjdheten.
            Beroende på ändamålet kan bokningssystemet omfatta olika tjänster såsom restaurangbord eller möteslokaler.
            Bokningssystemet är en kraftfull digital lösning som optimerar resursanvändningen och skapar en strukturerad
            och automatiserad hantering av bokningar, vilket i slutändan bidrar till att förbättra effektiviteten och servicekvaliteten för företaget.
        </p>
    </div>

    <div style="display: flex; flex-direction: column; background-color: cornflowerblue; border-radius: 20px; padding: 10px; text-align: center; width:100%;">
        <h2 class="display-4">Valfritt projekt</h2>
        <p style="font-size: 14px; border-radius: 20px; padding: 10px; background-color: cornflowerblue;">
            Har du en egen idé om vad du vill utveckla som du inte finner på denna webbplats? Fyll i kontaktformuläret så diskuterar vi möjligheter och förutsättningar att förverkliga den med mig som konsult!
        </p>

    </div>
    <div style="background-color: #4CAF50; width:400px; text-align:center; border-radius:12px;">
        <a class="nav-link text-light" asp-area="" asp-controller="Contact" asp-action="Index">Kontakta mig för offert</a>
    </div>
</div>
<br />

<div id="about" style="display: flex; background-color: cornflowerblue; border-radius: 12px; align-items:center;">

    <img src="\Pictures\ContactPictures\high_five.jpg" alt="Bild på mig" style=" object-fit:contain; border-radius: 12px; height: 100%; max-height: 200px; margin-right: 20px; flex-shrink: 0;" />

    <p id="about-p" style="font-size: 14px; margin-right: 20px; flex-grow: 1;">
        Relationsbyggande och att skapa win-win-situationer är fundamentala principer för mig som utvecklare.
        Jag tycker att varaktiga relationer bygger på ömsesidig tillit och värdefullt samarbete.
        Min övertygelse är att framgång inte bara handlar om att tillhandahålla tekniska lösningar, utan också om att bygga långsiktiga trygga partnerskap.
     
    </p>
</div>

isacstromberg_dev_site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - isacstromberg_dev_site</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/isacstromberg_dev_site.styles.css" asp-append-version="true" />
</head>
<body style=" background-image: url('/Pictures/background_image.png'); background-size: cover;">
    <header style="background-color :cornflowerblue;">
        <nav  class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-cornflowerblue border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Strömberg Studios</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Hem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Services" asp-action="Index">Tjänster</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="About" asp-action="Index">Om oss</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav ml-auto">
                        <li class="nav-contact">
                            <a class="nav-link text-light" asp-area="" asp-controller="Contact" asp-action="Index">Kontakt</a>
                        </li>

                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - isacstromberg_dev_site - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>